"""empty message

Revision ID: 46088edeea53
Revises: 4c3494b5944b
Create Date: 2025-08-20 22:31:19.886553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46088edeea53'
down_revision = '4c3494b5944b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_image_id', sa.String(), nullable=True),
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_image_id'], ['user_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_images_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_images_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)

    op.drop_table('user_image_tags')
    # ### end Alembic commands ###
